//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int file_identifier { get; set; }
        public string description { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual Users Users { get; set; }
    }
}
