//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int id { get; set; }
        public Nullable<int> id_chat { get; set; }
        public int sender { get; set; }
        public string content { get; set; }
        public Nullable<int> file_identifier { get; set; }
        public System.DateTime date { get; set; }
        public string type { get; set; }
    
        public virtual ChatRooms ChatRooms { get; set; }
        public virtual Files Files { get; set; }
        public virtual Users Users { get; set; }
    }
}
