//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id { get; set; }
        public Nullable<int> chat_id { get; set; }
        public int sender { get; set; }
        public string content { get; set; }
        public Nullable<int> file_identifier { get; set; }
        public System.DateTime date { get; set; }
        public string type { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual File File { get; set; }
        public virtual User User { get; set; }
    }
}
